# This is a basic workflow to help you get started with Actions

name: Build PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: LaTeX compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: bw-resume.tex
          compiler: latexmk
          args: -xelatex

      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "bw-resume Build Bot"
          git config user.email "<>"

      - name: Commit built PDF File
        run: |
          # Stage the file, commit and push
          git add *.pdf
          git commit -m "chore: CI Automation PDF Build"
          git push origin master
