# This is a basic workflow to help you get started with Actions

name: Build PDF

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: LaTeX compilation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bw-resume.tex
          latexmk_use_xelatex: true

      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "bw-resume Build Bot"
          git config user.email "<>"

      - name: Commit built PDF File
        run: |
          # Stage the file, commit and push
          git add *.pdf
          git commit -m "chore: CI Automation PDF Build"
          git push origin master
