
name: Build PDF

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: LaTeX compilation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bw-resume.tex
          latexmk_use_xelatex: true

      - name: Generate PNG Sample
        run: |
          sudo apt update
          sudo apt install poppler-utils
          pdftoppm -png ./bw-resume.pdf > bw-resume.png

      - name: Setup git config
        run: |
          git config user.name "bw-resume Build Bot"
          git config user.email "<>"

      - name: Commit built files
        run: |
          # Stage the file, commit and push
          git add *
          git commit -m "chore: CI Automation PDF Build"
          git push origin master
