
name: Build PDF

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: LaTeX compilation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: bw-resume.tex
          latexmk_use_xelatex: true

      - name: Generate PNG Sample
        run: |
          sudo apt update
          sudo apt install poppler-utils
          pdftoppm -png ./bw-resume.pdf > bw-resume.png

      - name: Setup git config
        run: |
          git config user.name "bw-resume Build Bot"
          git config user.email "<>"

      - name: Commit built files
        run: |
          # Stage the file, commit and push
          git add *.pdf *.png
          git commit -m "chore: CI Automation PDF Build"
          git push origin master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run release